# Generated by Django 4.1.2 on 2022-11-03 17:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='imageCat')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Niveaux')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=80)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='img')),
                ('statut', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professionnel', 'Professionnel'), ('Eleve', 'Eleve'), ('Autodidacte', 'Autodidacte')], max_length=80)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('profil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cours.profil')),
                ('bio', models.TextField()),
            ],
            bases=('cours.profil',),
        ),
        migrations.CreateModel(
            name='professeur',
            fields=[
                ('profil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cours.profil')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(default='samuel@gmail.com', max_length=254)),
                ('bio', models.TextField()),
            ],
            bases=('cours.profil',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mini_description', models.TextField(verbose_name='Minie description')),
                ('description', ckeditor.fields.RichTextField()),
                ('miniature', models.ImageField(upload_to='miniatures')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(upload_to='videos', verbose_name='Vidéo')),
                ('prix', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('identifiant', models.CharField(blank=True, max_length=100, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.category')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('miniature', models.ImageField(upload_to='miniature')),
                ('video', models.FileField(upload_to='videos')),
                ('document', models.FileField(upload_to='document')),
                ('date', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.theme')),
            ],
        ),
        migrations.CreateModel(
            name='historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Order par theme',
                'verbose_name_plural': 'Order par theme',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userame', models.CharField(max_length=50)),
                ('message', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.theme')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'commentaires',
            },
        ),
    ]
