# Generated by Django 4.1.2 on 2022-11-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_theme_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='timing',
            field=models.PositiveIntegerField(null=True, verbose_name='Durée de la formation en heure'),
        ),
    ]
